name: FastF1 Source
language: python
variables:
  - name: output_telemetry
    inputType: OutputTopic
    description: Car telemetry output topic
    defaultValue: f1-car-telemetry
    required: true
  - name: output_lap_data
    inputType: OutputTopic
    description: Lap timing output topic
    defaultValue: f1-lap-data
    required: true
  - name: output_position
    inputType: OutputTopic
    description: Position data output topic
    defaultValue: f1-position-data
    required: true
  - name: YEAR
    inputType: FreeText
    description: "e.g. 2023"
    defaultValue: "2023"
    required: false
  - name: ROUND
    inputType: FreeText
    description: "e.g. 1 for Bahrain GP"
    defaultValue: "1"
    required: false
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
