name: mongodb
language: docker
variables:
  - name: MONGO_INITDB_ROOT_USERNAME
    inputType: FreeText
    description: The root username to initialize MongoDB with
    defaultValue: admin
    required: true
  - name: MONGO_INITDB_ROOT_PASSWORD
    inputType: ProjectVariable
    description: The root password to initialize MongoDB with
    defaultValue: MONGO_ROOT_PASSWORD
    required: true
    secret: true
dockerfile: dockerfile
defaultFile: dockerfile
libraryItemId: mongodb
