name: OpenF1 Metadata Sink
language: python
variables:
  - name: input_meetings
    inputType: InputTopic
    description: OpenF1 meeting metadata
    defaultValue: openf1-meetings
    required: true
  - name: input_sessions
    inputType: InputTopic
    description: OpenF1 session metadata
    defaultValue: openf1-sessions
    required: true
  - name: input_drivers
    inputType: InputTopic
    description: OpenF1 driver list
    defaultValue: openf1-drivers
    required: true
  - name: CONFIG_API_URL
    inputType: FreeText
    description: Base URL of the Dynamic Configuration Manager REST API
    defaultValue: https://config-api-svc-quixdev-fastf1-dev.deployments-dev.quix.io
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
